apiVersion: v1
kind: Service
metadata:
  name: api-microservice
  namespace: prod
  labels:
    app: api-microservice
    environment: prod
spec:
  type: LoadBalancer
  selector:
    app: api-microservice
    environment: prod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
