apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: preprod
  labels:
    app: mongodb
    environment: preprod
spec:
  type: ClusterIP
  selector:
    app: mongodb
    environment: preprod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
