apiVersion: v1
kind: Service
metadata:
  name: api-microservice
  namespace: preprod
  labels:
    app: api-microservice
    environment: preprod
spec:
  type: ClusterIP
  selector:
    app: api-microservice
    environment: preprod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
