apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ephemeral
  labels:
    app: mongodb
    environment: ephemeral
spec:
  type: ClusterIP
  selector:
    app: mongodb
    environment: ephemeral
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
