apiVersion: v1
kind: Service
metadata:
  name: api-microservice
  namespace: ephemeral
  labels:
    app: api-microservice
    environment: ephemeral
spec:
  type: ClusterIP
  selector:
    app: api-microservice
    environment: ephemeral
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
