apiVersion: v1
kind: Service
metadata:
  name: api-microservice
  namespace: dev
  labels:
    app: api-microservice
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: api-microservice
    environment: dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
