apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: dev
  labels:
    app: mongodb
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: mongodb
    environment: dev
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
